@startuml

package "Facebook" {
  [AUTH]
  [FRIENDS]
}

package "Github" {
  [bestander]
}


package "Heroku Server" {

  [bestander] -- git
  git - [PONG-MMO-WWW]

  package PONG-MMO-WWW {
    [Index.html] --> [AUTH]
    [Index.html] --> [FRIENDS]
    [socket.io]
    [server.js]
    [server.js] --> [PONG-MMO-SERVER]


    package PONG-MMO-SERVER {

      package BOX2D-PONG {

        [PongGame] -> [BOX2D-COMMONJS]

        package BOX2D-COMMONJS {
        }

      }

      [PongSocket] -> [socket.io]
      [PongSocket] <- [PongGame]

      note left of [PongSocket]
        Several times a second
        gets the current game state
        from PongGame
        and sends the updates to client
        using socket.io connection
      end note


    }

    package PONG-MMO-CLIENT {
      [PongGameRenderer] -> [three.js]
      [ClientBootstrap] <-- [socket.io]
      [ClientBootstrap] -> [PongGameRenderer]
    }


    [Index.html] --> [ClientBootstrap]

    note right of [PongGame]
      Ball bounce simulation
      done here.
    end note

    note right of [SocketGameDriver]
      In the future
      game master implementation
      can use its own box2d for
      network lag compensation
    end note

    note right of [SocketGameDriver]
      Waits for server messages
      and orders the renderer
      to draw changes
    end note

    note left of [three.js]
      All game events are
      rendered using this engine
    end note

    note left of [Index.html]
      This web page aggregates all components
      and is delivered to users
    end note


  }

    [NODE.JS] --> [server.js]
    [server.js] --> [Index.html]

}

note left of git
  new release is pushed
  through git repository
end note

note right of [AUTH]
  No user management
  needs to be implemented
  Social Networks do the trick
end note


note right of [FRIENDS]
  No lobby is necessary,
  users will invite
  friends sending them a
  link to their game
end note

note left of [NODE.JS]
  Node.JS executes
  PONG-MMO-WWW/server.js
  after git deploy
end note






@enduml